# Generated by Django 2.2.4 on 2020-12-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('number_of_holes', models.IntegerField()),
                ('par', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='main.Course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole_number', to='main.Course')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_number', to='main.Course')),
            ],
        ),
    ]
