# Generated by Django 2.2.4 on 2020-12-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='main.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
